version: "3.7"

services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis-data:/data
    networks:
      - local

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecomz
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local

  migrate:
    image: migrate/migrate
    depends_on:
      - db
    volumes:
      - ./libs/db/migration:/migrations # Sesuaikan path migrasi
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/ecomz?sslmode=disable",
        "up",
      ]
    networks:
      - local

  auth-service:
    hostname: auth-service-host
    build:
      context: .
      dockerfile: ./services/auth-service/Dockerfile
    restart: on-failure
    networks:
      - local
    volumes:
      - ./services/auth-service/cmd/config.yml:/cmd/config.yml
    depends_on:
      - migrate
    environment:
      APP_NAME: "auth-rest-service"
      HTTP_PORT: "80"
      DSN: "postgres://postgres:postgres@db:5432/ecomz?sslmode=disable"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""

networks:
  local:

volumes:
  redis-data:
  postgres-data:
