name: Golang CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product-service, auth-service]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24
      - name: Install dependencies
        run: |
          cd services/${{ matrix.service }}
          go mod tidy
      - name: Build service
        run: |
          cd services/${{ matrix.service }}
          go build -v ./...
      - name: Build Docker image
        run: |
          docker build -t ecomz/${{ matrix.service }} -f ./services/${{ matrix.service }}/Dockerfile .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker image
        run: |
          docker push ecomz/${{ matrix.service }}
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ecomz/${{ matrix.service }}
            docker stop ${{ matrix.service }}
            docker rm ${{ matrix.service }}
            docker run -d --name ${{ matrix.service }} -p 8080:8080 ecomz/${{ matrix.service }}
